### ISSUE TITLE
Do not show demo

### ISSUE THREAD

**Issue by codauit** [matsim-org/evacuation-web-app#2]
Hi,
I accessed http://evac.vsp.tu-berlin.de/ and follow this step to show demo, but demo not show.
A popup with follow text "We are processing your query... Do not reload page! Results will be displayed automatically when ready." and do not show anything.
I am looking forward to hearing from you.
Thank you!
![image](https://user-images.githubusercontent.com/32630784/45755817-913b0980-bc49-11e8-82b2-f9c77f2f9191.png)

**Comment by kainagel** [comment]
Hello, we tried with Safari and with Chrome, and it is working for us.  Unfortunately, the maintainer of this is no longer with us, and has no time to work on this in his current job.  My intuition would be to try small areas and/or small agent numbers.  The attached comes back within approx 10sec.  Good luck.

![image](https://user-images.githubusercontent.com/8777649/45929363-7833a080-bf48-11e8-9767-2186a48f28f0.png)
